services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_API_BASE_URL: http://localhost:${PORT}/api
    container_name: buildlog_app
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    restart: unless-stopped